export const tokenImageMap: Record<string, string> = {
  SOL: "/tokens/SOL.png",
  USDC: "/tokens/USDC.png",
  TRUMP: "/tokens/TRUMP.png",
  JUP: "/tokens/JUP.png",
  WIF: "/tokens/WIF.png",
  BONK: "/tokens/BONK.png",
  JTO: "/tokens/JTO.png",
  RAY: "/tokens/RAY.png",
  PYTH: "/tokens/PYTH.png",
  HNT: "/tokens/HNT.png",
  W: "/tokens/W.png",
  MEW: "/tokens/MEW.png",
  POPCAT: "/tokens/POPCAT.png",
  ORCA: "/tokens/ORCA.png",
  ZEUS: "/tokens/ZEUS.png",
  KMNO: "/tokens/KMNO.svg",
  WBTC: "/tokens/WBTC.png",
  jupSOL: "/tokens/jupSOL.png",
  jitoSOL: "/tokens/jitoSOL.png",
  INF: "/tokens/INF.png",
  BIO: "/tokens/BIO.png",
  LAYER: "/tokens/LAYER.png",
  AIXBT: "/tokens/AIXBT.png",
  ACT: "/tokens/ACT.png",
  FART: "/tokens/Fartcoin.png",
};
